### ISSUE TITLE
Allow different Quality presets for buildSrcSet

### ISSUE THREAD

**Issue by davidgauch** [imgix/js-core#284]
**Is your feature request related to a problem? Please describe.**
I want to use variable quality images on our website, but I want to send lower quality images than the preset provided.

**Describe the solution you'd like**
I would like to be able to provide an object like this either when constructing the Client or when calling buildSrcSet:
`{ 1: 45,  2: 30,  3: 20,  4: 15}`

**Describe alternatives you've considered**
I've considered just copy pasting the Dist into my repo and editing the object. because it's pretty easy to spot in the dist.

**Comment by frederickfogerty** [comment]
Hey there @davidgauch 👋  thanks for opening this feature request. I've noted this down to discuss during our next team sync-up, and we'll get back to you after that!

**Comment by frederickfogerty** [comment]
Hey there @davidgauch, I wanted to follow up on this after discussing with the team. We are happy to support this and have placed it in our backlog. We will keep this issue up to date with any progress 👍

**Comment by frederickfogerty** [comment]
Fixed by #307 and released in `3.4.0` 🎉
