### ISSUE TITLE
Allow configure srcSet DPR generation

### ISSUE THREAD

**Issue by sylcastaing** [imgix/js-core#304]
Hello team,

My company and I want to cap DPR src-set generated by `buildSrcSet` function. We just need 1x and 2x to reduce DOM size and dowloaded image on mobile.

I think we can have an option `maxDPR` to cap srcet generation.

**Example :**
```js
{
  maxDPR: 2
}
```

Or maybe make `targetRatios` configurable with option inside the [_buildDPRSrcSet](https://github.com/imgix/js-core/blob/2eeea9f5aa73023e37a3ea4832f7b975f1f15c26/src/index.js#L194) fonction.

**Example :**
```js
{
  targetRatios: [1, 2]
}
```

**Comment by frederickfogerty** [comment]
Hi @sylcastaing, thanks for the issue! We are currently on a company holiday, so I will aim to get back to you in about two weeks.

**Comment by frederickfogerty** [comment]
Hey @sylcastaing, we are happy to support a `targetDPRRatios` type feature. Unfortunately we don't have time to implement this soon, so we will put this in our backlog and prioritise it. We will of course also happily accept a PR for this feature!

**Comment by sherwinski** [comment]
Resolved as part of #307
