### ISSUE TITLE
Do you support Management APIs?

### ISSUE THREAD

**Issue by vnugent** [imgix/js-core#322]
**Before you submit:**
-  [x] Please search through the [existing issues](https://github.com/imgix/js-core/issues?utf8=%E2%9C%93&q=is%3Aissue) to see if your question has already been discussed.

**Question**

It's not immediately clear whether Management Rest APIs are supported by this library `js-core` or will they be available in the future.  Can you please share your roadmaps/future plans?  Of course, we can write low-level REST API calls with `fetch()`, but having an official client library would definitely increase adoption in the React, Node.js dev community.

**Comment by vnugent** [comment]
I found the management library!  Please mention it from your official docs. Thanks.
https://github.com/imgix/imgix-management-js

**Comment by sherwinski** [comment]
Hey @vnugent,

Great point, I'll add a note to the documentation. Thanks 👍 
As for roadmap: we plan to roll out more official management client libraries over the course of this year. For right now we only offer the management-js library that you linked to.

**Comment by sherwinski** [comment]
Addressed in #324
